openapi: 3.0.3
info:
  title: Book API
  description: API for managing books
  version: 1.0.0
paths:
  /book:
    get:
      summary: Get a specific book
      description: Retrieve details of a book by its ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the book to retrieve
      responses:
        '200':
          description: Details of the book
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
        '404':
          description: Book not found
    post:
      summary: Create a new book
      description: Add a new book to the collection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewBookDTO'
        required: true
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookDTO'
        '400':
          description: Invalid input
    delete:
      summary: Delete a book
      description: Remove a book from the collection by its ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            format: int64
          description: The ID of the book to delete
      responses:
        '204':
          description: Book deleted successfully
        '404':
          description: Book not found
  /books-list:
    get:
      summary: Search for books by title
      description: Retrieve a list of books matching the title query
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
            minLength: 3
          description: The title to search for (minimum 3 characters)
      responses:
        '200':
          description: List of books matching the title
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookDTO'
        '204':
          description: No books found

components:
  schemas:
    BookDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: The unique identifier of the book
        title:
          type: string
          description: The title of the book
        description:
          type: string
          description: A brief description of the book
        authors:
          type: array
          items:
            type: string
          description: A list of authors of the book
        price:
          type: number
          format: float
          description: The price of the book
      required:
        - id
        - title
        - description
        - authors
        - price

    NewBookDTO:
      type: object
      properties:
        title:
          type: string
          description: The title of the book
        description:
          type: string
          description: A brief description of the book
        authors_pseudonym:
          type: array
          items:
            type: string
          description: A list of authors of the book
        price:
          type: number
          format: float
          description: The price of the book
      required:
        - title
        - description
        - authors_pseudonym
        - price
